/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://nwpd6a47izhgbfwykqy3suyzhu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-luhqmnefqbbbhh2xsx4czfylsi",
    "aws_cognito_identity_pool_id": "us-east-2:3ff72814-5048-4c84-911c-62f004e39c7d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hpwM12KLN",
    "aws_user_pools_web_client_id": "1fotrc665ri7rk2p5vef9vbdcq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
